# Generated by Django 4.2.11 on 2024-03-18 07:21

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=models.CASCADE,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        to="courses.Course",
                        on_delete=models.CASCADE,
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]