# Generated by Django 4.2.11 on 2024-03-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_enrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="enrollment_date",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="user",
        ),
    ]
