# Generated by Django 4.2.11 on 2024-03-19 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_remove_enrollment_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="name",
        ),
        migrations.RemoveField(
            model_name="course",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="course",
            name="user",
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student_name",
            field=models.CharField(default="ExampleName", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
